### ISSUE TITLE
Styles not purged in Next.js

### ISSUE THREAD

**Issue by benoror** [cast-corp/windmill-react-ui#1]
- `windmill-react-ui` version: `0.7.4`

### What happened:

Found out that in my Next.js app *some* Windmill styles were being purged away (aka tree-shaked) by `postcss` for some unknown reason **ONLY in Production env**

Here's a visual example

<img width="640" alt="Screen Shot 2022-08-18 at 12 17 03" src="https://user-images.githubusercontent.com/119117/186554413-689a7472-91a1-4d65-88b9-7705e6d1094c.png">

After a lot of digging I found out that windmill-specific styles weren't being purged properly. This issue opened in another windmill fork gave me the final hint: https://github.com/ngduc/windmill-react-ui-kit/issues/1

Related to these changes for Tailwind v3: https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

### What you did:

So as a workaround for now in my project I included the relative path to the windmill dist files to be purged:

<img width="688" alt="Screen Shot 2022-08-23 at 23 07 34" src="https://user-images.githubusercontent.com/119117/186554521-28dd541f-96dc-4bf0-a8a4-14fdb2e34f04.png">

### Relevant code or config: `tailwind.config.js`

```javascript
const defaultTheme = require('tailwindcss/defaultTheme');
const windmill = require('@cast-corp/windmill-react-ui/config')

module.exports = windmill({
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "../../node_modules/@cast-corp/windmill-react-ui/dist/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {},
  plugins: [],
})
```

(and tangentially I suspect [darkMode has to be specified as well](https://tailwindcss.com/docs/upgrade-guide#remove-dark-mode-configuration) to be backwards-compatible with windmill dark mode implementation)

### Suggested solution:

As far as I can tell the fix on your fork (and proposed PR) would be to more or less follow what's suggested in the other fork issue, with adjusted paths

**Comment by benoror** [comment]
For-the-record: Had a suspicion this might have something to do with the fact that I am using a Monorepo setup using Yarn workspaces (see Next.js docs: https://vercel.com/guides/deploying-yarn-monorepos-to-vercel)

Tested getting rid of it but confirmed same issue was happened, had to restore the content purging line but with different relative directory (bc lack of monorepo folder hierarchy):

```diff
--    "../../node_modules/@cast-corp/windmill-react-ui/dist/**/*.{js,ts,jsx,tsx}",
++    "./node_modules/@cast-corp/windmill-react-ui/dist/**/*.{js,ts,jsx,tsx}",
```

**Comment by awesomeunleashed** [comment]
Closing this, see discussion in #2.
